### PR TITLE
Client only & deprecation fix

### PR DESCRIPTION
**Pull request by Elix-x**
Basically, updated code to new forge standarts:
Menu mobs is client side only mod, no need to use it on server, thus
removed proxys and marked as clientSideOnly. Without this, if mod is
installed on server, forge will think that it must be installed on
clients, while it is actually not compulsory.
FMLCommonHandler.instance().bus() and MinecraftForge.EVENT_BUS are same
thing now.

### CODE REVIEW

**Comment by Elix-x** [comment]
Thanks!
Now, waiting for next update :wink: !

**Comment by bschoenmaeckers** [comment]
I will release the next update in a hour or so with some new features too :smile:

**Comment by Elix-x** [comment]
Awesome!

**Comment by bschoenmaeckers** [comment]
new release: http://minecraft.curseforge.com/projects/menumobs/files/2307752
Probably still under review.

**Comment by Elix-x** [comment]
No problem, i can wait.

**Pull request merged**
